name: Release
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: node
          package-name: ${{ github.event.repository.name }}
      # The logic below handles the npm publication:
      - uses: actions/checkout@v2
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: ${{ matrix.node-version }}
          # Use the Github Package registry
          registry-url: https://npm.pkg.github.com/
          scope: '@benddao'
      - name: Setup yarn
        if: ${{ steps.release.outputs.release_created }}
        run: npm install -g yarn
      - name: Setup Nodejs with yarn caching
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: yarn
      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_PACKAGES_REGISTRY_READ_ONLY }}
      - name: Test
        if: ${{ steps.release.outputs.release_created }}
        run: npm run ci:test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_PACKAGES_REGISTRY_READ_ONLY }}
      - name: Publish Package
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
